(function(){
'use strict';
function B(b,t,o){const a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();try{document.execCommand('copy'),b.innerHTML='✅ Скопировано!',b.classList.add('copied'),setTimeout(()=>{b.innerHTML=o,b.classList.remove('copied')},2000)}catch(e){alert('Не удалось скопировать.')}finally{document.body.removeChild(a)}}
function A(){document.querySelectorAll('.btn-copy').forEach(b=>{b.addEventListener('click',function(){const t=b.closest('.prompt-wrapper');if(!t)return;const o=t.querySelector('.prompt-box code');if(!o)return;const a=o.textContent||'',c=b.innerHTML;navigator.clipboard&&navigator.clipboard.writeText?navigator.clipboard.writeText(a).then(()=>{b.innerHTML='✅ Скопировано!';b.classList.add('copied');setTimeout(()=>{b.innerHTML=c;b.classList.remove('copied')},2000)}).catch(()=>B(b,a,c)):B(b,a,c)})})}
function C(){document.querySelectorAll('.image-slider').forEach(b=>{const t=b.querySelector('.slider-top-wrapper'),o=b.querySelector('.slider-handle'),a=o?o.querySelector('.slider-knob'):null;if(!t||!o||!a)return;let c=!1;function d(e){const i=b.getBoundingClientRect();let l=e-i.left;l<0&&(l=0),l>i.width&&(l=i.width);const s=l/i.width*100;t.style.width=s+'%',o.style.left=s+'%'}
function f(e){c=!0,a.style.cursor='grabbing',e.preventDefault();const i=e.type.includes('touch')?e.touches[0].clientX:e.clientX;d(i)}
function g(e){c&&(e.preventDefault(),d(e.type.includes('touch')?e.touches[0].clientX:e.clientX))}
function h(){c&&(c=!1,a.style.cursor='grab')}
a.addEventListener('mousedown',f),document.addEventListener('mousemove',g),document.addEventListener('mouseup',h),a.addEventListener('touchstart',f,{passive:!1}),document.addEventListener('touchmove',g,{passive:!1}),document.addEventListener('touchend',h),document.addEventListener('touchcancel',h)})}
function D(){const b=document.createElement('div');b.className='reading-progress-bar',document.body.prepend(b);function t(){const o=window.scrollY||document.documentElement.scrollTop,a=document.documentElement.scrollHeight-window.innerHeight;b.style.width=a>0?Math.min(100,Math.max(0,o/a*100))+'%':'0%'}window.addEventListener('scroll',t,{passive:!0}),t()}
function E(){const b=[{title:'Краш-тест ИИ на окраине цивилизации',url:'crash-test-3g.html'},{title:'Музыкальный сериал — Часть 1',url:'suno-music.html'},{title:'Топ-3 бесплатных ИИ',url:'top-3-free-ai.html'},{title:'Промпт-репетитор английского языка',url:'english-tutor-prompt.html'},{title:'Пакет выживания на 3G',url:'survival-pack-3g.html'}];const t=window.location.pathname.split('/').pop()||'';const o=b.filter(a=>a.url!==t);if(!o.length)return;const c=o.sort(()=>0.5-Math.random()).slice(0,3);const d=document.createElement('div');d.className='read-more-block';const f=document.createElement('h3');f.textContent='Читать также';d.appendChild(f);c.forEach(a=>{const e=document.createElement('a');e.className='read-more-link';e.href=a.url;e.textContent=a.title;d.appendChild(e)});const g=document.querySelector('article:last-of-type');g?g.insertAdjacentElement('afterend',d):document.body.appendChild(d)}
function F(){const b=window.location.pathname.split('/').pop()||'',t=b.replace('.html','')||'index';if(document.querySelector('.article-reactions'))return;const o=document.createElement('div');o.className='article-reactions';o.innerHTML='<div class="reactions-buttons"><button class="reaction-btn like" data-type="like">👍 <span class="count">0</span></button><button class="reaction-btn dislike" data-type="dislike">👎 <span class="count">0</span></button></div><div class="views-counter">👁️ <span class="count">0</span> просмотров</div>';const a=document.querySelector('.read-more-block');a?a.parentNode.insertBefore(o,a):(document.querySelector('article:last-of-type')||document.body).appendChild(o);const c=o.querySelector('.reaction-btn.like'),d=o.querySelector('.reaction-btn.dislike'),f=c.querySelector('.count'),g=d.querySelector('.count'),h=o.querySelector('.views-counter .count');let i={};try{i=JSON.parse(localStorage.getItem('blog_articles_stats'))||{}}catch(e){i={}}i[t]||(i[t]={views:0,likes:0,dislikes:0});i[t].views++;localStorage.setItem('blog_articles_stats',JSON.stringify(i));let l=localStorage.getItem('user_reaction_'+t);function j(){const e=i[t]||{views:0,likes:0,dislikes:0};f.textContent=e.likes;g.textContent=e.dislikes;h.textContent=e.views;l==='like'?(c.classList.add('active'),d.classList.remove('active')):l==='dislike'?(d.classList.add('active'),c.classList.remove('active')):(c.classList.remove('active'),d.classList.remove('active'))}
function k(e){const n=e.currentTarget.getAttribute('data-type'),s=i[t]||{views:0,likes:0,dislikes:0};if(l===n){n==='like'?s.likes=Math.max(0,s.likes-1):s.dislikes=Math.max(0,s.dislikes-1);l=null;localStorage.removeItem('user_reaction_'+t)}else if(l&&l!==n){l==='like'?s.likes=Math.max(0,s.likes-1):s.dislikes=Math.max(0,s.dislikes-1);n==='like'?s.likes++:s.dislikes++;l=n;localStorage.setItem('user_reaction_'+t,n)}else{n==='like'?s.likes++:s.dislikes++;l=n;localStorage.setItem('user_reaction_'+t,n)}i[t]=s;localStorage.setItem('blog_articles_stats',JSON.stringify(i));j()}c.addEventListener('click',k);d.addEventListener('click',k);j()}
function G(){A(),C(),D(),E(),F()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',G):G();
})();
